### ISSUE TITLE
not working after update to HA 2025.8.2

### ISSUE THREAD

**Issue by akeck** [binsentsu/home-assistant-solaredge-modbus#338]
Following Error after HA 2025.8.2 update:

Logger: homeassistant.setup
Source: setup.py:278
First occurred: 8:28:34 PM (1 occurrence)
Last logged: 8:28:34 PM

Setup failed for custom integration 'solaredge_modbus': Requirements for solaredge_modbus not found: ['pymodbus==3.6.9'].

**Comment by kajer** [comment]
Same, 8.2 update, and no more solaredge modbus integration

Logger: pymodbus.logging
Source: custom_components/solaredge_modbus/__init__.py:305
integration: SolarEdge Modbus ([documentation](https://github.com/binsentsu/home-assistant-solaredge-modbus))
First occurred: 16:31:42 (39 occurrences)
Last logged: 16:46:24

    Cancel send, because not connected!
    No response received after 3 retries, continue with next request

**Comment by rveupen** [comment]
After updating to 2025.8.2 I also get:
Setup failed for custom integration 'solaredge_modbus': Requirements for solaredge_modbus not found: ['py

Fixed by going backup to 2025.8.1 with this in Terminal:
ha core update --version 2025.8.1

**Comment by WimGo** [comment]
After upgrade to HA Core 2025.8.2 , Solaredge modbus could not be loaded in my installation as well, with this message:

> Logger:` homeassistant.util.package
> 
> Source: util/package.py:159
> First occurred: 11:28:24 AM (3 occurrences)
> Last logged: 11:28:24 AM
> Unable to install package pymodbus==3.8.3: × No solution found when resolving dependencies: ╰─▶ Because you require pymodbus==3.8.3 and pymodbus==3.9.2, we can conclude that your requirements are unsatisfiable.

**Comment by marcus198006** [comment]
Same here

Logger: homeassistant.setup
Quelle: setup.py:278
Erstmals aufgetreten: 15. August 2025 um 23:33:58 (1 Vorkommnis)
Zuletzt protokolliert: 15. August 2025 um 23:33:58

Setup failed for custom integration 'solaredge_modbus': Requirements for solaredge_modbus not found: ['pymodbus==3.6.9'].

**Comment by kajer** [comment]
After a lot of fiddling and leaving the plugin disabled for a few hours to
think about what it did, modbus is working with both my inverters on 8.2
and the latest hacs version of this plugin.

I read in another thread, turning modbis off/in on the inverter solved a
connection issue after upgrading.  Rather than do that, I just left the
plugin disabled a few hours to let the tvp sessions time out.

I also liberally restarted ha between each modbus plugin enable/disable
cycle.

Now it's all working again and showing inverter stats using the original
entities.

**Comment by akeck** [comment]
My fix for now:
edit /homeassistant/custom_components/solaredge_modbus/manifest.json
Change line 5 from:
`"requirements": ["pymodbus==3.6.9"],`

to:
`"requirements": ["pymodbus"],`

works for me.

**Comment by PascalWenders** [comment]
> My fix for now: edit /homeassistant/custom_components/solaredge_modbus/manifest.json Change line 5 from: `"requirements": ["pymodbus==3.6.9"],`
> 
> to: `"requirements": ["pymodbus"],`
> 
> works for me.
@akeck Which version do you use of solaredge_modbus
I have done your action, (changed"requirements": ["pymodbus==3.7.4"] to requirements": ["pymodbus] but the error in the log is:
**Setup failed for custom integration 'solaredge_modbus': Unable to import component: cannot import name 'pack_bitstring' from 'pymodbus.utilities' (/usr/local/lib/python3.13/site-packages/pymodbus/utilities.py)**

**Comment by WimGo** [comment]
Has anybody already tried upgrading HA to 2025.8.3?
Does ha-solaredge-modbus work properly with it?
Thanks in advance,

**Comment by akeck** [comment]
> Has anybody already tried upgrading HA to 2025.8.3? Does ha-solaredge-modbus work properly with it? Thanks in advance,

if you have the latest version (2.1.3) installed, it works.
However, somehow this custom integration does'nt get updated automatically, so you manually have to update it in HACS.

**Comment by mgambier** [comment]
As indicated by others installed 2.1.3 and restarted the inverter to get rid of the no connection issue.

**Comment by vikdb** [comment]
How does one restart an inverter?
