### ISSUE TITLE
Integration No Longer Working after Upgrading to 2026.7.0

### ISSUE THREAD

**Issue by twinkie0101** [binsentsu/home-assistant-solaredge-modbus#376]
Integration failed to start after upgrading to 2026.7.0; following message is from log:

Logger: homeassistant.setup
Source: setup.py:276
First occurred: 9:38:41 AM (1 occurrence)
Last logged: 9:38:41 AM

Setup failed for custom integration 'solaredge_modbus': Requirements for solaredge_modbus not found: ['pymodbus==3.11.2'].

**Comment by bjkluft** [comment]
Sanne here. 
The log is shown below:


Logger: homeassistant.setup
Source: setup.py:341
First occurred: 16:26:30 (1 occurrence)
Last logged: 16:26:30

Setup failed for custom integration 'solaredge_modbus': Unable to import component: cannot import name 'pack_bitstring' from 'pymodbus.pdu.pdu' (/usr/local/lib/python3.14/site-packages/pymodbus/pdu/pdu.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1091, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/solaredge_modbus/__init__.py", line 54, in <module>
    from .payload import BinaryPayloadDecoder, Endian
  File "/config/custom_components/solaredge_modbus/payload.py", line 20, in <module>
    from pymodbus.pdu.pdu import pack_bitstring, unpack_bitstring
ImportError: cannot import name 'pack_bitstring' from 'pymodbus.pdu.pdu' (/usr/local/lib/python3.14/site-packages/pymodbus/pdu/pdu.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1051, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1091, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/solaredge_modbus/__init__.py", line 54, in <module>
    from .payload import BinaryPayloadDecoder, Endian
  File "/config/custom_components/solaredge_modbus/payload.py", line 20, in <module>
    from pymodbus.pdu.pdu import pack_bitstring, unpack_bitstring
ImportError: cannot import name 'pack_bitstring' from 'pymodbus.pdu.pdu' (/usr/local/lib/python3.14/site-packages/pymodbus/pdu/pdu.py)

**Comment by Robertb160** [comment]
Unfortunately, I'm getting the same error.
HA now requires version 3.13.1
Is it compatible to this reqired version and can I update the   "requirements": ["pymodbus==3.11.2"], in manifest.json to 3.13.1 without issues?

**Comment by arthoog** [comment]
same error here.
updating the requirement to pymodbus==3.13.1 does not help
error: Unable to import component: cannot import name 'pack_bitstring' from 'pymodbus.pdu.pdu'

**Comment by Jay-El66** [comment]
Same problem on 2.2.1.

But look, a new version 2.3 is on the way, this is some info:

**Make compatible with pymodbus 3.13.1 used in HA 2026.7 
Update min HA version to 2026.7**

That is super fast!
So now waiting for the update to show up in HA

**Comment by twinkie0101** [comment]
Just updated and solved issue; closing issue. Thanks for quick update!
