### ISSUE TITLE
Active Power Limit throws AttributeError after update to 2.1.0

### ISSUE THREAD

**Issue by zucht** [binsentsu/home-assistant-solaredge-modbus#322]
After updating to version 2.1.0 and attempting to change the value of the active power limit entity, I encountered the following error: 

`AttributeError: 'SolaredgeModbusCoordinator' object has no attribute 'write_registers'`

After checking the debug logs, I noticed this error points to number.py, line 99, where the integration tries to call:

`response = self.hub.write_registers(...)`

The log message indicates that self.hub is a SolaredgeModbusCoordinator object, which does not have a write_registers method.

**What I tried:**
* Fully removed and reinstalled the integration.
* Restarted Home Assistant.
* Verified the issue is reproducible.
* Downgraded to version 2.0.5, which resolved the issue immediately.

**Relevant log snippet:**
```
  File "/config/custom_components/solaredge_modbus/number.py", line 99, in async_set_native_value
    response = self.hub.write_registers(
               ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SolaredgeModbusCoordinator' object has no attribute 'write_registers'
```
